name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
      env:
        PATH: /opt/devkitpro/devkitPPC/bin:/opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        DEVKITPRO: /opt/devkitpro
        DEVKITPPC: /opt/devkitpro/devkitPPC

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Build
        run: make

      - name: Prepare release zip
        run: |
          mkdir -p wii-shop-patcher
          cp boot.dol wii-shop-patcher/boot.dol
          zip -r wii-shop-patcher.zip wii-shop-patcher/

      - name: Create release
        uses: softprops/action-gh-release@v3.0.0
        with:
          tag_name: latest
          name: Latest Build
          files: wii-shop-patcher.zip
          prerelease: true
